### ISSUE TITLE
libbattery should be used

### ISSUE THREAD

**Issue by pavelmachek** [postmarketOS/charging-sdl#1]
SDL code will not work in all cases on N900, and it does not provide features such as battery temperature and current voltage. So I started libbattery:

https://github.com/pavelmachek/libbattery

Eventually, it would be good to turn it into shared library, so that we have one copy of code on the system.

**Comment by ollieparanoid** [comment]
> Eventually, it would be good to turn it into shared library, so that we have one copy of code on the system.

That makes sense!

**Comment by IanS5** [comment]
We could also make libbattery an optional dependency, at least for a little while. I'm giving it a try `SDL_TTF`. 

So if for whatever reason someone wanted the only dependency to be base SDL2 they could just compile without SDL2_ttf and libbattery.

**Comment by IanS5** [comment]
@pavelmachek just submitted a PR for having libbattary compile to a shared library. I've got a  branch ready for charging_sdl that will compile with that instead of SDL_power :D

**Comment by z3ntu** [comment]
In the end we probably will want to have libbattery as an optional **runtime** dependency, so the N900 can depend on libbattery and the rest of the devices don't. I think that would be the best solution.

**Comment by IanS5** [comment]
implementing that would actually be pretty easy I think. At the moment I have the libbattery `battery_fill_info` function running inside a timer callback, if `charging-sdl` used it's own battery info struct,  than we could just switch which callback is being used. Then everything in the main loop could stay exactly the same, and it would be trivial to add other methods too.

**Comment by MartijnBraam** [comment]
Isn't the point of libbattery that you put the device specific stuff in the library so you don't have to do that in all the applications?

**Comment by ollieparanoid** [comment]
In general, I would also prefer having less possible code paths, so using `libbattery` for everything would be cool with me. It will be a super lightweight library anyway.

*With that being said, I consider this to be a detail and don't have a strong opinion on it, as long as we make it work :+1:*

**Comment by IanS5** [comment]
For now why don't we just give the option to use either one, because libbattery is so new it may not cover some devices SDL does, and SDL (obviously) doesn't support at least one device libbattery does. Once both charging-sdl and libbattery mature a bit we could switch to just libbattery

**Comment by pavelmachek** [comment]
libbattery should support phones SDL supports.

No, it will not support ACPI based desktop or windows machine, but it
should support everything else.

**Comment by IanS5** [comment]
@ollieparanoid sorry this is completely the wrong place for this... but could I get write access on this repo?

**Comment by ollieparanoid** [comment]
Sure, in fact I already gave it to you, but you need to click [this link](https://github.com/postmarketOS/charging-sdl/invitations) (I guess it should have been sent via mail).
