### ISSUE TITLE
Burn-in on OLED screens

### ISSUE THREAD

**Issue by pavelmachek** [postmarketOS/charging-sdl#4]
Some phones (such as Nokia N9) have OLED screens, and those can be damaged by displaying same image on same place for too long... (burn-in). It would be nice to move stuff on the screen, randomly, to avoid that...

**Comment by ollieparanoid** [comment]
Good point! How about turning of the display a short time after the user tapped it with a finger?

**Comment by pavelmachek** [comment]
Turning off the display would help a lot, yes.

Having small icon moving around the screen would be even nicer --
black pixels do not eat power on OLED, so status information can be
visible all the time. (Not every phone has notification LED.)

**Comment by IanS5** [comment]
right now charing-sdl closes itself after 5 seconds when it's not in test mode. If that's too long for some phones we could make that time configurable with a command line flag or something (right now it's built in with the `UPTIME` macro)

**Comment by ata2001** [comment]
@pavelmachek I created PR #13 based on your idea.

**Comment by drebrez** [comment]
@pavelmachek could you please quantify your "too long"? 
The solution that ata2001 implemented is drawing a square at a different location every second, it's enough?
In postmarketOS the `charging-sdl` is now included and started when the charge mode is detected by default. It just start the `charging-sdl` which closes itself after 5 seconds and the user has to press the power key again to start it again. It doesn't start it with the flag to draw the square randomly, it might be a problem?

**Comment by pavelmachek** [comment]
5 seconds is definitely okay. 5 hours definitely would not be. 5
minutes would be hard to tell.
