### ISSUE TITLE
Consistent Style

### ISSUE THREAD

**Issue by IanS5** [postmarketOS/charging-sdl#7]
I've done a pretty aweful job of keep a consistent style with this project, would anyone mind using `indent` to fix it? It would be faily easy to get the target style (indent has the `-kr` flag for K&R style).

**Comment by ollieparanoid** [comment]
I think having a consistent style is a good idea! @craftyguy added a Travis job, which makes sure that linting is always correct for `osk-sdl` here: https://github.com/postmarketOS/osk-sdl/pull/67 - how about adopting the same script and style for `charging-sdl`?

**Comment by IanS5** [comment]
great! I coppied the necessary files over from `osk-sdl` and swapped out c++ specific parts of the scripts for c and every thing works fine. 

I'm going to request @pavelmachek to double check the open PR and once that's merged I'll fix up the code and merge my `styling` branch

**Comment by craftyguy** [comment]
Nice! Also, we use editorconfig is osk-sdl to insure consistent style when editing code. Feel free to steal that too :)

**Comment by ollieparanoid** [comment]
I've successfully enabled Travis for the repository:
https://travis-ci.org/postmarketOS/charging-sdl

However, I didn't know how to trigger it except when the PR was merged, so I merged it and it fails now on master, my bad. Anyway, from now on it should also work for new PRs.

**Comment by IanS5** [comment]
Awesome!
